# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev2+gc827d65.d20230829"
__version_tuple__ = version_tuple = (0, 1, "dev2", "gc827d65.d20230829")
